### ISSUE TITLE
Responsive Design: Checklist

### ISSUE THREAD

**Issue by jvanf** [frickerg/Web-Engineering-3#72]
- [ ] Getestet wird zwischen 375px (iPhone SE) und 1200px (Desktop) Viewport-Breite
- [ ] Inhalte dürfen nicht versteckt sein oder mit anderen überlappen
- [ ] Alignment von Listen & Tabellen muss bei geringer Breite bestehen bleiben
- [ ] font-size von 14px sollte nicht unterschritten werden (16px für Haupt-Content)
