### ISSUE TITLE
Access Control: Checklist

### ISSUE THREAD

**Issue by jvanf** [frickerg/Web-Engineering-3#79]
## Game

- [x] Jeder Benutzer hat sein eigenes Game
- [x] Games anderer Benutzer via Access Token auf API schützen
- [x] Lösungen erscheinen erst am Schluss auf der Resultats-Page

## Users

- [x] Benutzer können direkt in Variable verwaltet werden
  - Analog zu Cards und Games
  - Es braucht keine Registrierungs- oder Verwaltungs-Page für die Benutzer
- [x] Jeder Benutzer hat genau 1 Rolle (n:n-Beziehung nicht verlangt)
- [x] Hashing & Salting implementieren
  - Klartext-Passwörter in README-Datei (oder als Kommentar) für mich zum Testen hinterlegen

## Cards

- [x] Alle Benutzer haben die gleichen Stammdaten
- [x] Annahme: Cards werden nicht manipuliert wärend Spiele laufen. Können also im Backend-Model referenziert oder kopiert werden für ein Spiel.
- [x] Cards nur laden, wenn Benutzer Rolle "Admin" hat. Im UI ausblenden, sowie API via Access-Token schützen.
